---
title: "R Notebook"
output: html_notebook
---

```{r}
library(ggplot2)
```

```{r}
library(ggplot2)
data_elaborado <- read.csv("/Users/joseizammontt/Desktop/Universidad/master/thesis/codigo/Elaborados.csv", header=TRUE, stringsAsFactors=FALSE)
View(data_elaborado)
```

```{r}
graficar <- function(data,x, y1, y2) {
  p <- ggplot(data, aes(x = x))
  p <- p + geom_line(aes(y = y1, colour = "Precio"))
  
  # adding the relative humidity data, transformed to match roughly the range of the temperature
  p <- p + geom_line(aes(y = y2, colour = "Demanda"))
  
  # now adding the secondary axis, following the example in the help file ?scale_y_continuous
  # and, very important, reverting the above transformation
  p <- p + scale_y_continuous(sec.axis = sec_axis(~.*1, name = "Precio"))
  
  # modifying colours and theme options
  p <- p + scale_colour_manual(values = c("blue", "red"))
  p <- p + labs(y = "Demanda",
                x = "Semana",
                colour = "Datos")
  p <- p + theme(legend.position = c(0.85, 0.2))
  p
}
```

```{r}
locales <- unique(data_elaborado[,c("DESC_LOCALFISICO")])

```

```{r}
data_grafico <- data_elavorado %>%
  filter( COD_SKU==40252617, DESC_LOCALFISICO=="Angamos")

graficar(data_grafico,data_grafico$SEMANA,data_grafico$PrecioSKU40252617,data_grafico$DEMANDA)

```

```{r}

data_grafico <- data_elavorado %>%
  filter( COD_SKU==40887920, DESC_LOCALFISICO=="Angamos")

graficar(data_grafico,data_grafico$SEMANA,data_grafico$PrecioSKU40887920,data_grafico$DEMANDA)
```


```{r}
data_grafico <- data_elavorado %>%
  filter( COD_SKU==40905511, DESC_LOCALFISICO=="Angamos")

graficar(data_grafico,data_grafico$SEMANA,data_grafico$PrecioSKU40905511,data_grafico$DEMANDA)
```
